spring.datasource.url=jdbc:postgresql://localhost:5432/telegramDb
spring.datasource.username=worker
spring.datasource.password=telegram

# ?????????? ??????? ?? ????????? (?????????)
spring.profiles.active=local

spring.liquibase.change-log=classpath:liquibase/changelog-master.yml

# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto= update

spring.jpa.show-sql=true

# ???????? ??? ?????? (????? ????????????? ????????? ????????)
telegram.bot.token=placeholder-token