spring.datasource.url=jdbc:postgresql://localhost:5432/telegramDb
spring.datasource.username=worker
spring.datasource.password=telegram
telegram.bot.token=8079862512:AAHxXUO7O1mABMICApwJZmEUMbQxzg98Hhg

spring.liquibase.change-log=classpath:liquibase/changelog-master.yml

# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto= update

spring.jpa.show-sql=true
